¿Que es Python?

Es un lenguaje de programacion Orientado a Objetos, Programacion Imperativa, programacion funcional.

-Con una sintaxis sencilla de entender y aprender.

-Ampliamente utilizado en Ciencia e Ingenierias

-Multiples bibliotecas

Tipos Numerico

Disponemos de los tipos numericos y operaciones habituales.

In [81]:
#Si no colocamos el print se ejecutara todo el codigo, pero al momento de vizualisar resultados solo se muestra la ultima linea.
5 + 1 - 4 * 3
4/2
4//2

2

In [82]:
#Colocando print() muestra el resultado de cada linea.
print(5 + 1 - 4 * 3)
print(4/2)
print(4//2)

-6
2.0
2


Las diviones por cero lanzan un error

In [83]:
1/0

ZeroDivisionError: division by zero

Numero Complejos

In [84]:
(2+3j)

(2+3j)

Valor Absoluto de numeros

In [85]:
abs(-10)

10

In [86]:
(2+3j)*(1-5j)

(17-7j)

Potencia

In [87]:
2**2

4

Convertir a entero 

In [88]:
int(3.1416)

3

In [89]:
round(3.1416)

3

No puedo convertir complejos a numeros flotantes, python no reconoce la parte entera e imaginaria.

In [90]:
float(3+1j)

TypeError: can't convert complex to float

La asignacion de variables funciona igual que en otros lenguajes

In [91]:
a = 2**1
print(a)

2


In [96]:
a, b = 1, 2
print("el valor de a: ", a)
print("el valor de b: ", b)

el valor de a:  1
el valor de b:  2


Antes de continuar un detalle interesante sobre python es el Zen de Python.
Frases o ideas que los desarroladores colocaron.

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


Operadores de Comparacion

In [101]:
a , b , c = 1, 2, .05

In [102]:
print(a > c)
print(a < c)
print(a == c)
print(a != c)

True
False
False
True


Recordemos que los numeros complejos no se pueden ordenar ;)

In [103]:
a + 1j > 3 + 4j

TypeError: '>' not supported between instances of 'complex' and 'complex'

Algunos tipos de Variables en Python son:
    -str (Cadena)
    
    -list (Lista)
    
    -tuple (Secuencia de objetos inmutables)
    
    -dict (Diccionario)
    
    -int (Numero entero 1)
    
    -float (Numero flotante 1.0)
    
    -complex (Numero complejo 1+1j)
    
    -bool (Numero Boleano True o False)

In [104]:
#Type;Funcion para saber el tipo de objeto
Numericas = 1.0
print(type(Numericas))

Numericas = 1
print(type(Numericas))


<class 'float'>
<class 'int'>


In [105]:
#String
String = 'Hola Mundo'
type(String)

str

In [106]:
#Lista
lista = [1,2,3]
print(lista)
type(lista)

[1, 2, 3]


list

In [107]:
#Tuple
tuple_0 = ('1', '2', 3)
print(tuple_0)
type(tuple_0)

('1', '2', 3)


tuple

In [108]:
lista == tuple_0

False

In [109]:
#Diccionarios
Diccionario = {'Nombre': 'Carlos', 'Edad' : 25}
print(Diccionario)
type(Diccionario)

{'Nombre': 'Carlos', 'Edad': 25}


dict

In [110]:
#Operaciones con caracteres
Nombre = 'Carlos'
Nombre * 5

'CarlosCarlosCarlosCarlosCarlos'

Listas

Python tiene muchos tipos de estructura de datos,una de ellas es la lista. 
En algunos lenguajes de programación se las conocen como arreglos o matrices,
se caracterizan porque los elementos están entre corchetes y separados por una coma.

Una lista es una estructura de datos y un tipo de dato en python con características especiales.
Lo especial de las listas en Python es que nos permiten almacenar cualquier tipo de valor como enteros, cadenas y hasta otras funciones.

In [111]:
lista = [1,2,'a','b']
print(lista)

[1, 2, 'a', 'b']


Ver si un elemento se encuentra en una lista

In [112]:
'a' in lista

True

In [113]:
lista = [1,4,'Python',[7,10],4]

Para accede a los datos de una lista:

In [114]:
print(lista[0]) #El primer elemento de cualquier objeto es siempre 0.
print(lista[3]) #Es una lista que esta contenida en una lista
print(lista[3][1]) #Seleccion del elemento de la lista que vive en la lista.
#Para no estar esibiendo print para poder imprimir todos los elementos de un lista ocupamos un for
for elementos in lista:
    print(elementos)
print(lista)

1
[7, 10]
10
1
4
Python
[7, 10]
4
[1, 4, 'Python', [7, 10], 4]


Metodos de las listas.

Los Metodos son funciones que se pueden realizar sobre los objetos, en este caso los metodos de las listas son los siguientes.

In [115]:
#Metodos de las Listas.
lista.append(['nuevo_elemento',1,2]) #Agrega un elemento (puede ser una lista)
print("append: ", lista)

lista.extend([10,20,30]) #Agrega elemento la diferencia con append al momento de agregar una lista, cada elemento de esta lista se agrega como un elemento mas dentro de la otra lista.
print("extend: ", lista)

lista.remove(['nuevo_elemento',1,2]) #Elimina un elemento de la lista
print("remove: ", lista)

lista.index('Python')#Devuelve el numero del elemento que le pasemos

print("count: ", lista.count(4))  #Cuenta el numero de veces que se repite un elemento

lista.reverse()  #Invierte los elemenots
print("reverse : ", lista)


append:  [1, 4, 'Python', [7, 10], 4, ['nuevo_elemento', 1, 2]]
extend:  [1, 4, 'Python', [7, 10], 4, ['nuevo_elemento', 1, 2], 10, 20, 30]
remove:  [1, 4, 'Python', [7, 10], 4, 10, 20, 30]
count:  2
reverse :  [30, 20, 10, 4, [7, 10], 'Python', 4, 1]


Funciones incorporadas en python
Tiene un pequeño conjunto de funciones incorporadas enormemente utiles.

In [116]:
type(lista) #Devuelve el tipo del objeto
str(lista) #Convierte elementos a cadenas
dir(lista) #Devuelve los metodos para un objeto
abs(-5) #Valor absoluto
complex(1,5) #Numeros complejos
divmod(10,2) #Toma dos numeros y devuelve una pareja de numeros, el primero es el cociente de los argumentos y el segundo su residuo.
eval('1+1') #Convierte el texto y lo evalua como codigo python.
len(lista) #Numero de elementos en un objeto.

#Existen mas funciones.

8

In [117]:
Paquetes

Los paquetes son un conjunto de modulos, los modulos son archivos de codigo .py con variables, funciones y otros objetos.

En Python, cada uno de nuestros archivos .py se denominan módulos. Estos módulos, a la vez, pueden formar parte de paquetes.
Un paquete, es una carpeta que contiene archivos .py. Pero, para que una carpeta pueda ser considerada un paquete, debe contener un archivo de inicio llamado __init__.py. Este archivo, no necesita contener ninguna instrucción. De hecho, puede estar completamente vacío.

└── paquete 
    ├── __init__.py 
    ├── modulo1.py 
    ├── modulo2.py 
    └── modulo3.py
Los paquetes, a la vez, también pueden contener otros sub-paquetes:
 
└── paquete 
    ├── __init__.py 
    ├── modulo1.py 
    └── subpaquete 
        ├── __init__.py 
        ├── modulo1.py 
        └── modulo2.py
Y los módulos, no necesariamente, deben pertenecer a un paquete:

├── modulo1.py 
└── paquete 
    ├── __init__.py 
    ├── modulo1.py 
    └── subpaquete 
        ├── __init__.py 
        ├── modulo1.py 
        └── modulo2.py

SyntaxError: invalid syntax (<ipython-input-117-f0320f0429bc>, line 3)

Numpy es un ejemplo de paquete en Python.

¿Que es Numpy?

Es una paqueteria de python, sirve para facilitar la manipulacion de vectores y matrices.

Motivacion para Usar numpy.

    -Lob bucles son costosos

    -Eliminar bucles, vectorizar operaciones

    -Los bucles se ejecutan en python, las operaciones vectorizadas en C

    -Las operaciones entre arrays de NumPy se realizan elemento a elemento.

In [118]:
#Importacion de la paqueteria numpy
import numpy

In [119]:
a = numpy.arange(5) + 4 #Crea un array de 5 numeros y a cada elemeto le suma 4 
print(type(a))
print(a)

<class 'numpy.ndarray'>
[4 5 6 7 8]


Acceder a las funciones dentro de una paqueteria,la funcion norm se encuentra dentro del modulo linalg que se encuentra dentro de la paqueteria numpy. (De esta manera no traemos todas las funciones, teniendo implicaciones en la velocidad del codigo.)

La funcion norm, devuelve una de las ocho normas de matrices diferentes, o una de un número infinito de normas vectoriales.


In [120]:
print(numpy.linalg.norm(a)) 

13.7840487521


Una Practica habitual para trabajar con los paquetes es renombrandolos de la ssiguiente manera.

In [121]:
import numpy as np #Traemos numpy y lo llamamos np

In [122]:
print(np.linalg.norm(a))

13.7840487521


In [123]:
np.e
np.pi
np.log(2)

0.69314718055994529

Se puede renombrar tambien todo un modulo dentro de una paqueteria, de la siguiente manera.

In [124]:
from numpy import linalg as LA

In [125]:
print(LA.norm(a))

13.7840487521


Arrays de NumPy

¿Que es un Array?

Una de las estructuras de datos más fundamentales en cualquier idioma es el arrays (matriz).

Python no tiene una estructura de datos de matriz nativa, pero tiene una lista que es mucho más general y se puede usar como un arrays (matriz), multidimensional con bastante facilidad.


In [126]:
a = np.array([1,2,3,4]) #Los elementos son homogeneos
print(a)

[1 2 3 4]


In [127]:
a = np.array([1,2,"3"])  #Convierte todos en un mismo tipo
print(a)
a = np.array([1,2,"3"], dtype=float) #Forzo que todos tengan un tipo de elemento indicado
print(a)

['1' '2' '3']
[ 1.  2.  3.]


In [128]:
#Ejemplo: De la la velocidad de trabajar con arrays.

N, M = 100, 100
a = np.empty(10000).reshape(N,M)
b = np.random.rand(10000).reshape(N,M)
c = np.random.rand(10000).reshape(N,M)

In [129]:
%%timeit #Mide el tiempo que tarda en ejecutar el codigo
for i in range(N):
    for j in range(M):
        a[i,j] = b[i,j] + c[i,j]

6.15 ms ± 197 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [130]:
%%timeit 
a = b + c #Esta operacion se realiza elemento a elemento y se encuentra mas optimizado.

9.97 µs ± 148 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Indexacion de arrays
Una de las herramientas mas importantes al momento de trabajar con arrays es la indexacion. Consiste en seleecionar elementos aislados o secciones de un array. Vamos a ver la indexacion basica.

In [131]:
a = np.array([
    [1,2,3],
    [2,4,6]])
a

array([[1, 2, 3],
       [2, 4, 6]])

In [132]:
a[0]

array([1, 2, 3])

In [133]:
a[0][0]

1

In [134]:
a[0, 0]

1

In [135]:
a[0:2, 1:3] #No se toma en cuenta el ultimo elemento

array([[2, 3],
       [4, 6]])

In [136]:
a[:, 1:3]

array([[2, 3],
       [4, 6]])

In [137]:
a[0, 0:3:2] #Tomo los elementos que se encuentren en una posicion par.

array([1, 3])

In [138]:
a[0, ::2] #Es la misma forma de solo tomar los elementos de posiciones pares

array([1, 3])